service: ligue1-schedule
# used to be alexaOL stack...

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    keepOutputDirectory: false
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: dev
  logRetentionInDays: 7
  versionFunctions: false
  region: us-west-2
  timeout: 28
  httpApi:
    cors:
      allowedOrigins:
        - https://ligue1.jesse.co.ua
        - http://localhost:8080
      allowedHeaders:
        - Content-Type
        - x-timezone-offset
      allowedMethods:
        - GET
      allowCredentials: true
      maxAge: 6000
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:BatchGetItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - { "Fn::Join": [ "", [ "arn:aws:dynamodb:", { "Ref": "AWS::Region" }, ":", { Ref: "AWS::AccountId" }, ":table/", "BeIN_schedule" ] ] }

functions:
  getSchedule:
    handler: functions/GetSchedule/handler.schedule
    events:
      - httpApi:
          method: GET
          path: /ligue1/schedule/{day}
